# Generated by Django 3.1.1 on 2020-09-02 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.PositiveIntegerField(verbose_name='User ID')),
                ('name', models.TextField(verbose_name='User name')),
            ],
            options={
                'verbose_name': 'Profiles',
            },
        ),
    ]
